//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Country {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Country() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppTour.UI.Web.WebPortal.Resources.Views.Country.Country", typeof(Country).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar País.
        /// </summary>
        public static string Apagar {
            get {
                return ResourceManager.GetString("Apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende eliminar o país.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código País (Número).
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do País.
        /// </summary>
        public static string CountryHeader {
            get {
                return ResourceManager.GetString("CountryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome País para Mostrar.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O País irá ser apagado e não há retorno..
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza?.
        /// </summary>
        public static string DeleteMessage1 {
            get {
                return ResourceManager.GetString("DeleteMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar País.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Erro {
            get {
                return ResourceManager.GetString("Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string ISO {
            get {
                return ResourceManager.GetString("ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO3.
        /// </summary>
        public static string ISO3 {
            get {
                return ResourceManager.GetString("ISO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Países.
        /// </summary>
        public static string Lista {
            get {
                return ResourceManager.GetString("Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome País.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo País.
        /// </summary>
        public static string Novo {
            get {
                return ResourceManager.GetString("Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não pode apagar o país porque se encontram registos associados a ela..
        /// </summary>
        public static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
    }
}
