//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Point {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Point() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppTour.UI.Web.WebPortal.Resources.Views.Point.Point", typeof(Point).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Atributos.
        /// </summary>
        public static string AddAtributos {
            get {
                return ResourceManager.GetString("AddAtributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributos.
        /// </summary>
        public static string Atributos {
            get {
                return ResourceManager.GetString("Atributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordenada.
        /// </summary>
        public static string Coordenada {
            get {
                return ResourceManager.GetString("Coordenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Ponto.
        /// </summary>
        public static string Editar {
            get {
                return ResourceManager.GetString("Editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Pontos.
        /// </summary>
        public static string Lista {
            get {
                return ResourceManager.GetString("Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Atributos.
        /// </summary>
        public static string LstAttributos {
            get {
                return ResourceManager.GetString("LstAttributos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Ponto.
        /// </summary>
        public static string Novo {
            get {
                return ResourceManager.GetString("Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.º Telefone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do Ponto.
        /// </summary>
        public static string PointHeader {
            get {
                return ResourceManager.GetString("PointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonte URL.
        /// </summary>
        public static string SourceURL {
            get {
                return ResourceManager.GetString("SourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontos.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topicos.
        /// </summary>
        public static string Topicos {
            get {
                return ResourceManager.GetString("Topicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topicos.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
    }
}
