//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchProfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchProfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppTour.UI.Web.WebPortal.Resources.Views.SearchProfile.SearchProfile", typeof(SearchProfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo de Eventos (dias).
        /// </summary>
        public static string EventsSearchDays {
            get {
                return ResourceManager.GetString("EventsSearchDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de Perfis de Pesquisa.
        /// </summary>
        public static string Lista {
            get {
                return ResourceManager.GetString("Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar Novo Perfil de Pesquisa.
        /// </summary>
        public static string Novo {
            get {
                return ResourceManager.GetString("Novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Pesquisa {
            get {
                return ResourceManager.GetString("Pesquisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distância dos Pontos (KM).
        /// </summary>
        public static string PointsRangeDistance {
            get {
                return ResourceManager.GetString("PointsRangeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfis de Pesquisa.
        /// </summary>
        public static string SeachProfileHeader {
            get {
                return ResourceManager.GetString("SeachProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critério de Pesquisa.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tópicos.
        /// </summary>
        public static string SearchProfileTopics {
            get {
                return ResourceManager.GetString("SearchProfileTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisa.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
