//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Attribute {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Attribute() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppTour.UI.Web.WebPortal.Resources.Views.Attribute.Attribute", typeof(Attribute).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Atributo.
        /// </summary>
        public static string AddAttrBtn {
            get {
                return ResourceManager.GetString("AddAttrBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicione Atributos ao Ponto.
        /// </summary>
        public static string AddAttrDesc {
            get {
                return ResourceManager.GetString("AddAttrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave.
        /// </summary>
        public static string AddAttrKey {
            get {
                return ResourceManager.GetString("AddAttrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Atributos.
        /// </summary>
        public static string AddAttrTitle {
            get {
                return ResourceManager.GetString("AddAttrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dados.
        /// </summary>
        public static string AddAttrType {
            get {
                return ResourceManager.GetString("AddAttrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string AddAttrValue {
            get {
                return ResourceManager.GetString("AddAttrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar ao Ponto.
        /// </summary>
        public static string BackToPoint {
            get {
                return ResourceManager.GetString("BackToPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Atributo.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Atributo irá ser apagado e não há retorno..
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Atributo.
        /// </summary>
        public static string EdtAttrTitle {
            get {
                return ResourceManager.GetString("EdtAttrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editado com Sucesso!.
        /// </summary>
        public static string EdtSucess {
            get {
                return ResourceManager.GetString("EdtSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEYPAIR.
        /// </summary>
        public static string KeyPair {
            get {
                return ResourceManager.GetString("KeyPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faltam dados!.
        /// </summary>
        public static string MissingParams {
            get {
                return ResourceManager.GetString("MissingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionado com sucesso!.
        /// </summary>
        public static string Sucess {
            get {
                return ResourceManager.GetString("Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atributos.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dados Invalido!.
        /// </summary>
        public static string TypeDontMatch {
            get {
                return ResourceManager.GetString("TypeDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existem registos associados ao atributo..
        /// </summary>
        public static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALUE_STRING.
        /// </summary>
        public static string Value_string {
            get {
                return ResourceManager.GetString("Value_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Dados.
        /// </summary>
        public static string ValueType {
            get {
                return ResourceManager.GetString("ValueType", resourceCulture);
            }
        }
    }
}
